### ISSUE TITLE
Recurring http 429 error - too many requests

### ISSUE THREAD

**Issue by AnttiSim** [rOpenGov/pxweb#151]
I have moderate lists of data that I fetch from Statistics Finland with get_pxweb_data(). Unfortunately that gets aborted with http error 429 - too many requests. This is not easy to replicate, because the dataset where I get stuck varies each time. We have also identified the possible culprit as our IT service providers firewall protocols that got some re-configuration recently.

In order to get this work this I played with your source code and tried to solve this by using httr::RETRY function, which will automatically pause the process with similar errors. Nevertheless, the problem remains. I have now doubts that what gets reported to me as 429 error is somehow something else.

I could push my commits to you if you find that useful. During several test runs I encountered one occasion with httr::RETRY output, which could indicate that httr::RETRY could solve some problems caused by request limits.

**Comment by MansMeg** [comment]
Thank you for you suggestion! I'm currently rewriting the whole package and I hope this problem will be solved.

I guess that the problem is not your firewall, 429 is an error message from the API saying that you have called the API too many times. This should be controlled by the pxweb package with the get_pxweb_data(). But there can be two bugs:
1) The code handling calls and keeping track of time may be flawed. I hope this is not the case. If you have an example on how you replicate the error I could check this.
2) The number of calls using a time points are parameters for each specific API. If Stat Finland has changed these a litte these bugs can occur. I will later this week try to add an aoutmatic check for these parameters. In PXWEB later than R1 2014 it is possible to ping the API for these parameters so I can easily check this.

As soon as I have a new function to get data I can send it to you and you can test the development version if you want. To see if that has the same error. Since Im currently rewriting the package this would be highly appreciated.

**Comment by MansMeg** [comment]
Hmmm. Status code 429 is related to too many requests:
https://httpstatuses.com/429
It should not be possible for you to get this due to firewall settings on your side. 

Stat Finland has actually changed their parameters but only increased the value size. So this should not be an issue. Hence it is highly likely a problem within the pxweb package. Hopefully this is solved with the new pxweb structure. Could you create a reproducible example I can run to reproduce the bug?

**Comment by AnttiSim** [comment]
All right. I'll send you the example by email - I somehow cannot include attachments here.

You should probably check the 'httr' function RETRY, which is designed to address 429 and other cases where pausing the process could prevent total abortion. I took your source code and amended all httr's GET and POST calls with RETRY. Unfortunately it did not solve my issue.

**Comment by MansMeg** [comment]
Thats great! Thank you! Ill look into it asap and see what happens. Ill let you know as soon as I know.

**Comment by MansMeg** [comment]
Any news on this issue @AnttiSim ?
